### ISSUE TITLE
Working with audio files as well?

### ISSUE THREAD

**Issue by bonyboy** [bubonic/TGC.bundle#1]
Hi, I would like to use this for an audio course, but I didn't see audio files mentioned.

Thanks!

**Comment by bubonic** [comment]
Hi and thanks for your interest. Unfortunately this agent does not support the TGC Audio courses. I believe a separate agent would need to be created to handle the audio courses as it requires different processing in PLEX. At this time I don't plan on implementing/creating a new agent for the audio courses. Your interest has been logged and if there is enough support I may consider coding such an agent.

Thanks.
