### ISSUE TITLE
Any chance of locating a poster for the lectures?

### ISSUE THREAD

**Issue by Supertramp78** [bubonic/TGC.bundle#3]
thanks for fixing the lecture title and descriptions. 
Looks like Great Courses stopped creating vertical posters for their courses unless there is a buried source for these guys that I'm not aware of. 

Well, take that back, the last one I did FOUND one so I may have to try some old ones again.

**Comment by bubonic** [comment]
Okay. Let me know. My plex server died a few weeks ago, so I have to re-add everything I have - luckily the TGC courses are on my GDrive so I didn't lose any of those.  I did the first course today and it grabbed the poster. On their website they have the poster hidden in the html and I don't think they even display them anymore, but the TGC agent still knows where to find them on their site. It's possible for new courses there may be no poster. 

I haven't fooled around with this in over a year, but I'll be getting back to them soon. I'll leave this ticket open in the meantime.

**Comment by Supertramp78** [comment]
Thanks for the response. I thought you were gone since you stopped posting
on the PLEX forum. I'm not all that aware of how Github works as a process.
My bad. Yeah, it looks like it is finding stuff from somewhere. I have no
idea where. Recently there have been a bunch of one off sample lectures
that don't have posters so I had to make some for those. Thanks for your
efforts on this.

**Comment by bubonic** [comment]
> I thought you were gone since you stopped posting on the PLEX forum. 

Nah, I'm not going anywhere special. I float in and out of of things, but some places I remain. There is a lot to keep up with, but you can always get a hold of me on here. 

Best.
