### ISSUE TITLE
Windows

### ISSUE THREAD

**Issue by willemsjawt** [bubonic/TGC.bundle#5]
Made a backup and a clean Plex installation, with a proper log I hope you can work with. @bubonic

I did extract TGC.bundle out of the master and placed it in the Plug-ins location. 

Have Firefox 60.0 and Geckodriver 0.26 installed, did change the code to the right paths.
Using PlexMediaServer-1.21.1.3876

Cheers
[com.plexapp.agents.tgc.log](https://github.com/bubonic/TGC.bundle/files/5873258/com.plexapp.agents.tgc.log)

**Comment by bubonic** [comment]
It looks like there are issues with Firefox. I ran into this error several times before I got the right versions. Could you check the plugin location for a file called "geckodriver.log" and post that here.

**Comment by willemsjawt** [comment]
[geckodriver.log](https://github.com/bubonic/TGC.bundle/files/5875005/geckodriver.log)

Thanks for responding so fast :)

**Comment by bubonic** [comment]
> [geckodriver.log](https://github.com/bubonic/TGC.bundle/files/5875005/geckodriver.log)
> 
> Thanks for responding so fast :)

Okay. From that log, it has to do with either WebGL or headless mode. An easy fix may be to run it in full mode for Windows users or disable WebGL and stay in headless mode. I don't know what WebGL is so I'll have to loook into that and see if it is okay to disable. This would all be so much easier if I had a Windows machine. But oh well, you'll have to be patient with me as we figure this out. 

Thanks.

**Comment by Supertramp78** [comment]
Well I tried the updated version on my windows machine and the same thing happened. Plex died. Doing a backup restore again. I think I may have to bid farewell to this amazing plug-in. Dang it.

**Comment by bubonic** [comment]
> Well I tried the updated version on my windows machine and the same thing happened. Plex died. Doing a backup restore again. I think I may have to bid farewell to this amazing plug-in. Dang it. 

That really sucks. You are my biggest fan lol. I'm not sure what you mean by PLEX dying, but I guess I'll take your word for it. Sorry to see you go.

**Comment by Supertramp78** [comment]
if one of you hold ups is the lack of a windows machine, want to use mine? if you are familiar with the remote desktop program Anydesk, i can let you take comtrol of mine if you want. you can tinker to your heart's content. the worst thing that can happen is i restore from my backup.

what happens is after i install everything and restart plex, nothing sees it.  not accessible. uninstall all the stuff and restart and plex starts and you still cant see it .

anyway, this fan would love to help you figure this out if you are interested. let me know how to email you with details if you want to give it a go . what time zone are you in? Im central

**Comment by bubonic** [comment]
> [geckodriver.log](https://github.com/bubonic/TGC.bundle/files/5875005/geckodriver.log)
> 
> Thanks for responding so fast :)

Well, there is no way to disable WebGL in firefox currently. A little research indicated we can do this in chrome in headless mode. However, we need WebGL to render TGC website. From what I gather on the chromium bugs pages, it appears that they use a GL rending engine for use in headless mode.

This suggests a possible solution for our dear Windows users. That is, we have to force the option for Windows users to use chrome within the agent. I'll edit some of the code tomorrow to force chrome on windows. The only thing is, testing this will be a bitch. I wish I had a windows developer helping with this. 

I'm making this an open solution for any forkers. I will force chrome, but I'm not going to be going back and forth with anyone if it doesn't work on the first go. They major reason is I can't make a code change, push it to git, and wait for responses. That would drive any coder nuts not having the proper hardware and software to test it for themselves. 

Once I force chrome, the best you can hope for if it doesn't work on the first go, is to try various versions of chrome. I will try to find a specific version based on minimum guidelines. 

Without a windows dev, I can't make this work. We will just have to wait until one comes along,if it doesn't work after I make the next push to git.

**Comment by bubonic** [comment]
> if one of you hold ups is the lack of a windows machine, want to use mine? if you are familiar with the remote desktop program Anydesk, i can let you take comtrol of mine if you want. you can tinker to your heart's content. the worst thing that can happen is i restore from my backup.
> 
> what happens is after i install everything and restart plex, nothing sees it.  not accessible. uninstall all the stuff and restart and plex starts and you still cant see it .
> 
> anyway, this fan would love to help you figure this out if you are interested. let me know how to email you with details if you want to give it a go . what time zone are you in? Im central  

I'll get at you in the next couple of days. I'm taking a breather for now.

**Comment by Supertramp78** [comment]
no problem. It isn't like this is your JOB or anything. LOL.

**Comment by willemsjawt** [comment]
@Supertramp78 @bubonic 
So I got it working using this version of Firefox:
https://ftp.mozilla.org/pub/firefox/releases/52.8.1esr/win64/en-GB/

**Comment by bubonic** [comment]
> @Supertramp78 @bubonic 
> So I got it working using this version of Firefox:
> https://ftp.mozilla.org/pub/firefox/releases/52.8.1esr/win64/en-GB/

For realz? Nuts! There is a guideline saying Firefox 60.0 is the minimum version that would work with the version of Selenium and Geckdriver I used. I won't question a good thing. That's awesome!

**Comment by bubonic** [comment]
Be sure to dl the new commit I made on Tuesday. It includes the totally radical search function that I spent all day Monday compiling the library for the **ancient** PLEX python framework.

**Comment by bubonic** [comment]
I'd clone in it a different location so you still have the version of the agent that is currently working for you... Just in case
